# Generated by Django 5.2.4 on 2025-07-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تحلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='BCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تحلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بوم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='PESTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تحلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Porter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تحلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='SWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تحلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='ValueProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تحلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='AnsoffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اقدام')),
                ('strategy', models.CharField(choices=[('market_penetration', 'نفوذ در بازار'), ('product_development', 'توسعه محصول'), ('market_development', 'توسعه بازار'), ('diversification', 'تنوع\u200cسازی')], max_length=50, verbose_name='استراتژی')),
                ('weight', models.FloatField(default=1, verbose_name='وزن')),
                ('ansoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='strategic_tools.ansoff')),
            ],
        ),
        migrations.CreateModel(
            name='BCGItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('market_growth', models.FloatField(verbose_name='رشد بازار')),
                ('market_share', models.FloatField(verbose_name='سهم بازار')),
                ('quadrant', models.CharField(choices=[('Star', 'ستاره'), ('CashCow', 'گاو شیرده'), ('QuestionMark', 'علامت سؤال'), ('Dog', 'سگ')], max_length=20, verbose_name='چهارچوب')),
                ('weight', models.FloatField(default=1, verbose_name='وزن')),
                ('bcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='strategic_tools.bcg')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('Key Partners', 'شریک\u200cهای کلیدی'), ('Key Activities', 'فعالیت\u200cهای کلیدی'), ('Key Resources', 'منابع کلیدی'), ('Value Propositions', 'ارزش پیشنهادی'), ('Customer Relationships', 'روابط با مشتری'), ('Channels', 'کانال\u200cها'), ('Customer Segments', 'بخش\u200cهای مشتری'), ('Cost Structure', 'ساختار هزینه'), ('Revenue Streams', 'جریان درآمد')], max_length=50, verbose_name='نوع بلوک')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('weight', models.FloatField(default=1, verbose_name='وزن')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='strategic_tools.canvas')),
            ],
        ),
        migrations.CreateModel(
            name='PESTELFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Political', 'سیاسی'), ('Economic', 'اقتصادی'), ('Social', 'اجتماعی'), ('Technological', 'تکنولوژیک'), ('Environmental', 'محیطی'), ('Legal', 'حقوقی')], max_length=20)),
                ('text', models.CharField(max_length=255, verbose_name='متن')),
                ('weight', models.FloatField(default=1, verbose_name='وزن')),
                ('pestel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='strategic_tools.pestel')),
            ],
        ),
        migrations.CreateModel(
            name='PorterFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Rivalry', 'رقابت درون\u200cصنعت'), ('Suppliers', 'قدرت تأمین\u200cکنندگان'), ('Buyers', 'قدرت خریداران'), ('NewEntrants', 'تهدید تازه\u200cواردها'), ('Substitutes', 'تهدید محصولات جایگزین')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('weight', models.FloatField(default=1, verbose_name='وزن')),
                ('porter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='strategic_tools.porter')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='قوت')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='اهمیت')),
                ('swot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='strategic_tools.swot')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='فرصت')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='اهمیت')),
                ('swot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='strategic_tools.swot')),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='تهدید')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='اهمیت')),
                ('swot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='strategic_tools.swot')),
            ],
        ),
        migrations.CreateModel(
            name='ValuePropositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_segment', models.CharField(max_length=100, verbose_name='بخش مشتری')),
                ('gains', models.TextField(verbose_name='دستاوردها')),
                ('pains', models.TextField(verbose_name='دردها')),
                ('products_services', models.TextField(verbose_name='محصولات / خدمات')),
                ('weight', models.FloatField(default=1, verbose_name='وزن')),
                ('value_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='strategic_tools.valueprop')),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='ضعف')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='اهمیت')),
                ('swot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='strategic_tools.swot')),
            ],
        ),
    ]
